spring:
  application:
    name: demo
  profiles:
    active: local
  config:
    import:
      - classpath:application-common.yml
      - classpath:application-database.yml

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO

app:
  environment: LOCAL
  pool-size: 10
